name: Paper Presentation
description: Propose to share a papar in a scheduled meeting.
title: "[Presentation] "
labels: [kind/paper]
body:
- type: textarea
  attributes:
    label: Title
    description: |
      Title of the paper.
  validations:
    required: true

- type: textarea
  attributes:
    label: Link
    description: |
       Provide the source link of this paper
  validations:
    required: true

- type: textarea
  attributes:
    label: Year
    description: |
      Year of the paper published.
  validations:
    required: true

- type: textarea
  attributes:
    label: Author and affiliation
    description: |
      Author and affiliation of the paper.
  validations:
    required: true

- type: textarea
  attributes:
    label: Conference or Journal
    description: |
      The conference or journal of the paper published.
  validations:
    required: true

- type: textarea
  attributes:
    label: Rank
    description: |
      Rank(generally CCF) of the conference or journal of the paper published.
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Keywords
    description: |
       Please refer to Opendium or Mindmap to select several keywords for this paper.     
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Selecting Reason
    description: |
       Please provide the reason why you select to share this paper.
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Supplementary
    description: |
       Any other information you wish to provide.
  validations:
    required: false 
