name: Paper Translation
description: Propose to translate a paper
title: "[Translation] "
labels: [kind/translation]
body:
- type: textarea
  attributes:
    label: Title
    description: |
      Title of the paper to be translated.
  validations:
    required: true

- type: textarea
  attributes:
    label: Source Link
    description: |
      Please provide the link of the original article.
  validations:
    required: true

- type: textarea
  attributes:
    label: Translation Link
    description: |
      Please provide the link of the translated article.
  validations:
    required: true
    
